name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: yarn install --immutable

      - name: Contracts — format check
        run: yarn foundry:lint

      - name: Contracts — tests
        run: yarn foundry:test

      - name: Frontend — lint
        run: yarn next:lint --max-warnings=0

      - name: Frontend — types
        run: yarn next:check-types

      - name: Frontend — build
        run: yarn next:build
